### ISSUE TITLE
Will Testament

### ISSUE THREAD

**Issue by Imperial-Guard** [bram2202/mqtt-watermeter#1]
Hi Bram, great script. Currently I'm trying to add a Will Testament to your existing code and some other small updates. But somehow after a x seconds my Will testament is set to "no" again, 

Any thougs on this? 

I changed in MQTTPublisher.ccp line 41: 

`    clientConnected = client.connect(clientId.c_str(), MQTT_USER_NAME, MQTT_PASSWORD, MQTT_TOPIC "/online", 0, true, "no" );`

and on line 57: 

`      client.publish(MQTT_TOPIC "/online", "yes", true);`

Thanks in advance

**Comment by bram2202** [comment]
@Imperial-Guard did you mean line 39 and 54?

**Comment by Imperial-Guard** [comment]
yes correct :) Looked at my own code but offcourse the lines are different my bad :)

**Comment by bram2202** [comment]
looks ok, but i didnt make the `MQTTPublisher.ccp`. I cant test it now as i dont have a spare ESP.
I borrowed the code from https://github.com/jantenhove/GoodWeLogger
