### ISSUE TITLE
Boot loop with nodemcu v3

### ISSUE THREAD

**Issue by bruvv** [bram2202/mqtt-watermeter#2]
Nice work but for some reason I am getting a boot loop on my nodemcu v3 any idea what I can do differently to get this to work :) ?

**Comment by bram2202** [comment]
Can u post some debug logs here? without it it is difficult to find the cause.

**Comment by bruvv** [comment]
Of course but there was no debug. Didn't even boot. Do you want that pre boot memory error stuff ?

**Comment by bram2202** [comment]
oh, the code was written for a `ESP8266`, maybe one of the used libs doesn't support the `ESP-12E`
I cant test this theory because i don't have a `ESP-12E` at hand.

**Comment by bruvv** [comment]
Thanks for the answer I do have a ESP-12E so that might be it. will debug when I moved homes :)
